
services:
###########################
# Setup the Apache container
###########################
    httpd:
        container_name: ${NAME_PROJECT}_httpd
        restart: always
        image: httpd:${VALUE_HTTPD_VERSION}
        ports:
            - ${VALUE_HTTPD_PORT}:80
        volumes:
            - ./.docker/containers/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./.docker/containers/apache/vhosts/:/usr/local/apache2/conf/vhosts
            - ./.dockertmp/tmp/httpd/:/usr/local/apache2/tmp/httpd:rw
            - ./.dockertmp/log/httpd/:/usr/local/apache2/logs:rw
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: ${NAME_PROJECT}_php
        restart: always
        build: 
            context: ./.docker/images/php/
            args:
                - VALUE_PHP_VERSION=${VALUE_PHP_VERSION}
                - VALUE_XDEBUG_VERSION=${VALUE_XDEBUG_VERSION}
                - VALUE_COMPOSER_VERSION=${VALUE_COMPOSER_VERSION}
                - VALUE_MHSEND_VERSION=${VALUE_MHSENDMAIL_VERSION}
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./.env:/usr/local/apache2/www/${FOLDER_CONFIG}/.env:rw
            - ./config/config.php:/usr/local/apache2/www/${FOLDER_CONFIG}/config.php:rw
            - ./config/sgbd_config.php:/usr/local/apache2/www/${FOLDER_CONFIG}/sgbd_config.php:rw
            - ./config/filedotenv.php:/usr/local/apache2/www/${FOLDER_CONFIG}/filedotenv.php:rw
            - ./config/data:/docker-entrypoint-initdata.d:rw
            - ./config/dockercron:/var/docker/cron/dockercron:rw
            - ./.docker/containers/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
            - ./.docker/containers/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/containers/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./.docker/containers/php/mailhog.ini:/usr/local/etc/php/conf.d/mailhog.ini:ro
            - ./.dockertmp/log/php:/var/log/docker/php:rw
            - ./.dockertmp/log/xdebug:/var/log/docker/xdebug:rw
            - ./.dockertmp/tmp/php:/var/tmp/docker/php:rw
        environment:
            - TZ=${VALUE_TIMEZONES}
            - PHP_FOLDER_DATA=data
            
###########################
# Setup the Database (MariaDB) container
###########################
    mariadb:
        container_name: ${NAME_PROJECT}_mariadb
        restart: always
        image: mariadb:${VALUE_MARIABD_VERSION}
        volumes:
            - ./.docker/containers/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
            - ./config/sgbd_data:/docker-entrypoint-initdb.d/:rw
            - ./.dockertmp/log/mariadb:/var/log/mariadb:rw
            - ./.dockertmp/tmp/mariadb:/var/tmp/mariadb:rw
            - ./.dockertmp/mariadb_data:/var/lib/mysql
        environment:
            - TZ=${VALUE_TIMEZONES}
            - MYSQL_DATABASE=${SGBD_DATABASE}
            - MYSQL_ROOT_PASSWORD=${SGBD_PASSWORD}
            
###########################
# Setup the PhpMyAdmin container
###########################
    myadmin:
        container_name: ${NAME_PROJECT}_phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:${VALUE_PHPMYADMIN_VERSION}
        environment:
            - PMA_PORT=3306
            - PMA_HOST=${NAME_PROJECT}_mariadb
            - PMA_USER=root
            - PMA_PASSWORD=${SGBD_PASSWORD}
        ports:
            - ${VALUE_PHPMYADMIN_PORT}:80
        depends_on: 
            - mariadb
            
###########################
# Setup the mailhog container
###########################
    mailhog:
        build:
            context: .docker/images/mailhog
            args:
                - VALUE_MHOG_VERSION=${VALUE_MAILHOG_VERSION}
        container_name: ${NAME_PROJECT}_mailhog
        restart: always
        volumes:
            - ./.dockertmp/mailhog:/mailhog
            - ./config/email_data:/docker-entrypoint-initdata.d:rw
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/mailhog
        ports:
            - ${VALUE_MAILHOG_PORT}:8025
            
